"""empty message

Revision ID: 44eb724e54b7
Revises: bf6a81fdd2f2
Create Date: 2023-02-22 17:55:41.650755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44eb724e54b7'
down_revision = 'bf6a81fdd2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('appointment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
