"""empty message

Revision ID: 65706db3e40d
Revises: 879ec35b6af8
Create Date: 2023-02-22 20:18:20.520898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65706db3e40d'
down_revision = '879ec35b6af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
