"""empty message

Revision ID: a596411575fb
Revises: 65706db3e40d
Create Date: 2023-02-22 20:38:31.739645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a596411575fb'
down_revision = '65706db3e40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_constraint('Show_detail_id_fkey', type_='foreignkey')
        batch_op.drop_column('detail_id')

    op.drop_table('Showdetail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Show_detail_id_fkey', 'Showdetail', ['detail_id'], ['id'])

    op.create_table('Showdetail',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Showdetail_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Showdetail_pkey')
    )
    # ### end Alembic commands ###
